# Generated by Django 4.2.2 on 2024-04-26 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Reclamo'], [1, 'Consulta sobre un servicio'], [2, 'Mensaje positivo'], [3, 'Sugerencia']], verbose_name='Tipo de consulta')),
                ('mensaje', models.TextField(max_length=1000, verbose_name='Mensaje')),
                ('avisos', models.BooleanField(verbose_name='Avisos')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Servicio')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('imagen', models.ImageField(null=True, upload_to='static/img/servicios', verbose_name='Imagen del servicio')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
        ),
    ]
