# Generated by Django 4.2.2 on 2024-04-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoServicio',
        ),
    ]
