# Generated by Django 4.2.2 on 2024-05-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_tipoconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.tipoconsulta', verbose_name='Tipo Consulta'),
        ),
    ]
