# Generated by Django 4.2.2 on 2024-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Precio'),
        ),
    ]
