# Generated by Django 4.2.2 on 2024-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_servicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripción'),
        ),
    ]
