# Generated by Django 4.2.2 on 2024-05-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_categoria_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
